from . import viewMy
from . import battle
from . import revansh
from . import statistics
from . import withFriend
from . import toBack
from . import admin
from . import help
from . import start
from . import echo